[package]
name = "example"
version = "0.1.0"
authors = ["Lukas Lueg <lukas.lueg@gmail.com>"]
edition = "2018"

[dependencies]
restruct = { path = "../impl", version = "0.1" }
restruct_derive = { path = "../derive", version = "0.1" }
libc = "0.2"

[build-dependencies]
cc = "1.0"
